# Generated by Django 5.0.4 on 2024-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=255, verbose_name='Из токого пользователя')),
                ('to_user', models.CharField(max_length=255, verbose_name='На такого пользователя')),
                ('mount', models.CharField(max_length=255, verbose_name='Сколько денег помтупили')),
            ],
        ),
    ]
