# Generated by Django 5.0.4 on 2024-05-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_adress',
            field=models.CharField(default=1, max_length=12, verbose_name='ID кошелка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password_confirm',
            field=models.CharField(max_length=2, verbose_name='Подтвердите пароль'),
        ),
    ]
