# Generated by Django 5.0.4 on 2024-05-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytransfer',
            name='from_user',
            field=models.CharField(max_length=255, verbose_name='От пользователя'),
        ),
        migrations.AlterField(
            model_name='historytransfer',
            name='to_user',
            field=models.CharField(max_length=255, verbose_name='К пользователя'),
        ),
    ]
